language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - sudo sh ./.travis/install_dependencies.sh
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - api/vendor/bin/phpunit --configuration ./api/phpunit.xml --verbose
